# Copyright 2019 the .NET Foundation
# Licensed under the MIT License
#
# Initial pipeline file derived from the Azure Pipelines ASP.NT sample file; cf.
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactStagingDirectory)\WWTUserWebsite.zip'
    publishLocation: 'pipeline'
    artifactName: WWTUserWebsite.zip
  displayName: Publish web deployment bundle artifact

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactStagingDirectory)\WWTUserWebsite.deploy.cmd'
    publishLocation: 'pipeline'
    artifactName: WWTUserWebsite.deploy.cmd
  displayName: Publish sample deployment command artifact

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'aas@wwtadmindotnetfoundation'
    appType: 'webApp'
    WebAppName: 'wwtuserstaging'
    packageForLinux: '$(build.artifactStagingDirectory)\WWTUserWebsite.zip'